In [3]:
import numpy as np 
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data = np.random.rand(7,4)
data


array([[0.36104143, 0.38845241, 0.97207231, 0.39532482],
       [0.17383672, 0.54990696, 0.02918577, 0.12202089],
       [0.20313739, 0.88757898, 0.68898546, 0.85925992],
       [0.12149698, 0.19175666, 0.04518024, 0.2427662 ],
       [0.51233823, 0.46653682, 0.83913871, 0.70445111],
       [0.57389461, 0.91539106, 0.48623514, 0.36899322],
       [0.76332354, 0.02793367, 0.95043234, 0.30150312]])

**Boolean indexler true yada false dönen indexlerdir.

In [7]:
names == 'Bob'


SyntaxError: invalid syntax (<ipython-input-7-bcb7eb4a1d05>, line 2)

**namesin içinde Bob olan elementler True döner diğerleri False

In [5]:
data[names == 'Bob']

array([[0.36104143, 0.38845241, 0.97207231, 0.39532482],
       [0.12149698, 0.19175666, 0.04518024, 0.2427662 ]])

In [8]:
data[names == 'Bob',2:]

array([[0.97207231, 0.39532482],
       [0.04518024, 0.2427662 ]])

In [9]:
data[names == 'Bob',3]

array([0.39532482, 0.2427662 ])

In [10]:
mask = (names =='Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [11]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [12]:
data[mask]

array([[0.36104143, 0.38845241, 0.97207231, 0.39532482],
       [0.20313739, 0.88757898, 0.68898546, 0.85925992],
       [0.12149698, 0.19175666, 0.04518024, 0.2427662 ],
       [0.51233823, 0.46653682, 0.83913871, 0.70445111]])

In [13]:
data <0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [28]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 5.30363302, -0.56920616,  2.45646109],
       [-0.56920616,  5.09216344,  0.16266401],
       [ 2.45646109,  0.16266401,  3.28212663]])

arr ve transpozunu matrix çarpımı yaptık.

In [32]:
arr = np.arange(16).reshape((2,2,4))

In [33]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

 swapaxes: matrisin hem eksenlerini değiştiryor hemde transpozunu alıyor.
 transpoze: sadece transpozunu alıyoruz.
 reshape: matrisi istediğimiz bir şekilde yeniden eksenlerini düzenliyoruz.
 
 

In [34]:
arr = np.arange(10)

In [35]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [36]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [45]:
np.random.seed(1023)

what is random seed?
her random seedi değiştirdiğimizde random olarak istediğimiz sayı farklı bir sonuç vericektir

In [52]:
x = np.random.rand(8)


In [47]:
np.random.seed(102)

In [48]:
y = np.random.rand(8)

In [49]:
x

array([0.91406979, 0.63007121, 0.50893322, 0.05289729, 0.03998864,
       0.73333206, 0.66635096, 0.84684819])

In [50]:
y

array([0.59768158, 0.6759869 , 0.29928174, 0.73074027, 0.57873939,
       0.80901767, 0.1672485 , 0.31214497])

In [51]:
np.maximum(x, y)

array([0.91406979, 0.6759869 , 0.50893322, 0.73074027, 0.57873939,
       0.80901767, 0.66635096, 0.84684819])

her bir elemenetin öbür matristeki yerindeki elemente bakar büyük olanı yazar.

In [56]:
z = np.maximum(x, y)

In [57]:
for i in range(len(x)):
    print(x[i],y[i],z[i])

0.3579315539685616 0.5976815849360632 0.5976815849360632
0.49174729907120607 0.675986904372284 0.675986904372284
0.49019823958695485 0.29928174100970184 0.49019823958695485
0.8944098875868252 0.7307402679090343 0.8944098875868252
0.1824105253678282 0.5787393910609689 0.5787393910609689
0.3611620851279358 0.8090176696206909 0.8090176696206909
0.8105914603555655 0.16724850414891546 0.8105914603555655
0.33344682960956373 0.3121449685769 0.33344682960956373


In [58]:
x>y

array([False, False,  True,  True, False, False,  True,  True])

In [59]:
(x>0.5) | (y > 0.5)

array([ True,  True, False,  True,  True,  True,  True, False])

In [60]:
(x>0.5) & (y > 0.5)

array([False, False, False,  True, False, False, False, False])

In [61]:
xarr = np.array([1.1, 1.2,1.3, 1.4, 1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True, False, True, True, False])

conditioanal logic boolean bir arrayin true ve false göre kullanıldığı yerdeki mantığı sağlayıp sağlamaması 

In [63]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

where:  condition oluyorsa x elementini alır diğer türlü y elementini alır.

In [65]:
arr = np.random.randn(4,4)

rand:0 ile 1 arasında dağılım
randn: meani 0 ve variance ı 1 olan dağılım     

In [66]:
arr

array([[-1.71226271,  0.13611989, -0.46444399,  0.05097984],
       [ 1.44789871,  0.59313848, -0.75561568, -0.62716553],
       [ 0.88403489,  0.16271776, -2.50281287,  0.41079099],
       [ 0.72875041,  0.0291402 , -0.29105246,  0.31429308]])

In [67]:
np.where(arr > 0, 2, -2)

array([[-2,  2, -2,  2],
       [ 2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [ 2,  2, -2,  2]])

In [68]:
np.where(arr > 0,2,arr)

array([[-1.71226271,  2.        , -0.46444399,  2.        ],
       [ 2.        ,  2.        , -0.75561568, -0.62716553],
       [ 2.        ,  2.        , -2.50281287,  2.        ],
       [ 2.        ,  2.        , -0.29105246,  2.        ]])

In [70]:
x = 10*np.random.rand(8)

In [71]:
y = 10*np.random.rand(8)

In [72]:
np.where((x > 5)& (y<5),0, np.where((x>5),1,np.where((y>5), 2, 3)))

array([0, 1, 3, 2, 0, 2, 0, 1])

In [73]:
for i in range(len(x)):
    print(x[i],y[i])

5.198191415311251 1.3205688809438398
5.057643519558775 7.148644177265679
3.4856035962341094 3.4666291477011715
0.7084276340102036 6.144114906565457
5.759820075952406 2.874896343689425
4.017127015045218 9.85569710372433
9.114150610072178 2.7221317635707463
8.088855117422277 8.19391518109579


In [75]:
x = np.arange(8).reshape((2,2,2))

In [76]:
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
b = np.add.reduce(x,0)

In [78]:
b

array([[ 4,  6],
       [ 8, 10]])

In [79]:
c = np.add.reduce(x,1)

In [80]:
c

array([[ 2,  4],
       [10, 12]])

In [81]:
x = np.ones((5,))
x

array([1., 1., 1., 1., 1.])

In [82]:
y = np.linspace(-2,2,5)

In [83]:
y

array([-2., -1.,  0.,  1.,  2.])

In [84]:
np.outer(x,y)

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

In [86]:
x = np.ones((4,4))

In [87]:
x[1,:]=x[1,:]*2

In [88]:
x[2,:]=x[2,:]*3

In [89]:
x[3,:]=x[3,:]*4

In [90]:
x

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [91]:
x.mean(axis=1)

array([1., 2., 3., 4.])

In [92]:
x.mean(axis=0)

array([2.5, 2.5, 2.5, 2.5])

In [93]:
x.mean(1)

array([1., 2., 3., 4.])

In [94]:
x.mean(0)

array([2.5, 2.5, 2.5, 2.5])

In [95]:
x.sum()

40.0

In [96]:
x.sum(0)

array([10., 10., 10., 10.])

In [97]:
x.sum(1)

array([ 4.,  8., 12., 16.])

In [98]:
x


array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [99]:
x.cumsum()

array([ 1.,  2.,  3.,  4.,  6.,  8., 10., 12., 15., 18., 21., 24., 28.,
       32., 36., 40.])

In [100]:
x.cumsum(0)

array([[ 1.,  1.,  1.,  1.],
       [ 3.,  3.,  3.,  3.],
       [ 6.,  6.,  6.,  6.],
       [10., 10., 10., 10.]])

In [101]:
x.prod()

331776.0

In [102]:
x.prod(0)

array([24., 24., 24., 24.])

In [103]:
x.cumprod(0)

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 6.,  6.,  6.,  6.],
       [24., 24., 24., 24.]])

In [104]:
x= np.random.randint(1,100,20).reshape(5,4)

In [105]:
x

array([[69, 95, 85, 67],
       [24, 75, 73, 95],
       [65, 38, 57, 50],
       [ 2, 67, 24, 77],
       [81,  4, 13, 42]])

In [107]:
x.sort(0)
x

array([[ 2,  4, 13, 42],
       [24, 38, 24, 50],
       [65, 67, 57, 67],
       [69, 75, 73, 77],
       [81, 95, 85, 95]])

In [110]:
x.sort(1)

x.sort(0) diyince sütunları küçükten büyüğe sıralıyor.
x.sort(1) yazınca satırları küçükten büyüğe sıralıyor.
np.sort(x) hem satır hem sütunları sıralar.

In [111]:
x

array([[ 2,  4, 13, 42],
       [24, 24, 38, 50],
       [57, 65, 67, 67],
       [69, 73, 75, 77],
       [81, 85, 95, 95]])

In [112]:
np.sort(x)

array([[ 2,  4, 13, 42],
       [24, 24, 38, 50],
       [57, 65, 67, 67],
       [69, 73, 75, 77],
       [81, 85, 95, 95]])

In [114]:
arr = np.array([0,1,7,12,15])

In [115]:
arr.searchsorted(9)

3

9 değeri array  küçükten büyüğe sıralandığında 3.elemanın yerine gelirdi.

In [116]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5], dtype=int64)